[package]
name = "classlink-checker"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = "1.10"
clap = { version = "4.5", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[dev-dependencies]
tempfile = "3.10"
